In [2]:
import numpy as np

b=np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [3]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [6]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
my_lst_1=[1,2,3,4,5]
my_lst_2=[6,7,8,9,10]
my_lst_3=[9,8,7,6,5]

arr=np.array([my_lst_1,my_lst_2,my_lst_3])

In [17]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [9]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  9,  8],
       [ 7,  6,  5]])

After using reshape make sure that it will have the same numbers that in the list or else it gave error

Indexing

In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9])


In [13]:
arr[-1]

np.int64(9)

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[1:3,2:4]

array([[8, 9],
       [7, 6]])

In [19]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [20]:
arr=np.arange(0,10,2)

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

Copy Function

In [ ]:
arr[3:]=100

In [ ]:
arr

array([  0,   2,   4, 100, 100])

In [ ]:
arr1=arr

In [ ]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [ ]:
arr

array([  0,   2,   4, 500, 500])

In [ ]:
arr1=arr.copy()

In [ ]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [ ]:
val=2
arr[arr<300]

array([0, 2, 4])

In [ ]:
# Create arrays and reshape it

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr1=np.arange(0,10).reshape(2,5)

In [ ]:
arr2=np.arange(0,10).reshape(2,5)

In [ ]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.random.rand(3,3)

array([[0.20201296, 0.8420801 , 0.30419768],
       [0.6520348 , 0.06165042, 0.73297316],
       [0.10974583, 0.38245251, 0.63163139]])

In [ ]:
arr_ex=np.random.randn(3,3)

In [ ]:
arr_ex

array([[-0.6840202 ,  0.34089668, -0.34853709],
       [-2.1144717 , -0.91113669,  1.35394127],
       [-0.06950751, -2.05917028,  1.73980997]])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.zeros((2,3))


In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((3,3))
arr4


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:

a=np.array([1,2])
b=np.array([1.])


In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
arr=np.array([1,2,3,4,5])
arr1=arr.astype(float)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr1

array([1., 2., 3., 4., 5.])

In [ ]:
arr.itemsize

8

In [ ]:
arr1.itemsize


8

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
lista=range(100)
lista

range(0, 100)

In [22]:
arr=np.arange(25).reshape(5,5)

In [23]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[1:4,3:4]

array([[ 8],
       [13],
       [18]])

In [ ]:
arr[2:3,2:3]

array([[12]])

In [ ]:
arr

In [24]:
arr[1:3,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr[3:,3:]

array([[18, 19],
       [23, 24]])

Numpy Array Operation

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([6,5,4,3,2,1])

In [ ]:
arr1+arr2

array([7, 7, 7, 7, 7, 7])

In [ ]:
arr1*arr2

array([ 6, 10, 12, 12, 10,  6])

In [ ]:
arr2>3

array([ True,  True,  True, False, False, False])

In [ ]:
#dot product

arr1.dot(arr2)

np.int64(56)

In [ ]:
arr1.max()

np.int64(6)

In [ ]:
arr1.min()

np.int64(1)

In [ ]:
arr2.sum()

np.int64(21)

In [ ]:
arr1.sum (axis=0)

np.int64(21)

In [ ]:
arr4=np.arange(0,9).reshape(3,3)

In [ ]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr4.min(axis=0)

array([0, 1, 2])

In [ ]:
arr4.max(axis=1)

array([2, 5, 8])

In [ ]:
arr4.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
arr4.sum(axis=1)

array([ 3, 12, 21])

In [ ]:
arr4.sum()

np.int64(36)

In [ ]:
arr4.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
arr4.sum(axis=1)

array([ 3, 12, 21])

In [ ]:
arr4.mean()

np.float64(4.0)

In [ ]:
np.median(arr4)

np.float64(4.0)

In [ ]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr4.ndim

2

**Reshaping Numpy Array**

In [ ]:
# Using ravel we get matrices 2,3,4,n dimensional in 1d
np.ravel(arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**transpose() is like Row becomes column and column become Row**

In [ ]:
arr4.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
arr5=np.arange(12,18).reshape(2,3)

In [ ]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

**Fancy Indexing**

In [28]:
arr6=np.arange(24).reshape(6,4)

In [29]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
arr6[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [30]:
arr6[[2,3],[1,2]]

array([ 9, 14])

**Boolean Array**

In [ ]:
import numpy as np


In [ ]:
arry=np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [ ]:
arry

array([[21, 78, 13, 95, 32],
       [72, 24, 98, 30, 50],
       [17, 91, 30, 51, 95],
       [27,  6, 65, 14, 72]], dtype=int32)

In [ ]:
arry[0][2]

np.int32(13)

In [ ]:
arry>50

array([[False,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False,  True, False,  True,  True],
       [False, False,  True, False,  True]])

In [ ]:
# Indexing using Boolean array
arry[arry>50]

array([78, 95, 72, 98, 91, 51, 95, 65, 72], dtype=int32)

In [ ]:
arry[(arry>50) & (arry%2==0)]

array([78, 72, 98, 72], dtype=int32)

In [ ]:
arry[(arry>50) & (arry%2==0)]=-1

In [ ]:
arry

array([[21, -1, 13, 95, 32],
       [-1, 24, -1, 30, 50],
       [17, 91, 30, 51, 95],
       [27,  6, 65, 14, -1]], dtype=int32)