In [14]:
import numpy as np

b=np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [15]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.shape

(5,)

In [5]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
my_lst_1=[1,2,3,4,5]
my_lst_2=[6,7,8,9,10]
my_lst_3=[9,8,7,6,5]

arr=np.array([my_lst_1,my_lst_2,my_lst_3])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  9,  8],
       [ 7,  6,  5]])

After using reshape make sure that it will have the same numbers that in the list or else it gave error

Indexing

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9])


In [11]:
arr[-1]

np.int64(9)

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [22]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [ ]:
arr[1:3,2:4]

array([[8, 9],
       [7, 6]])

In [ ]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [ ]:
arr=np.arange(0,10,2)

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

Copy Function

In [ ]:
arr[3:]=100

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [ ]:
arr1=arr

In [ ]:
arr1[3:]=500
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 9  8  7  6  5]]


In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [ ]:
arr1=arr.copy()

In [ ]:
print(arr)
arr1[3:]=1000
print(arr1)

[0 2 4 6 8]
[   0    2    4 1000 1000]


In [ ]:
val=2
arr[arr<300]

array([0, 2, 4, 6, 8])

In [ ]:
# Create arrays and reshape it

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
arr1=np.arange(0,10).reshape(2,5)

In [26]:
arr2=np.arange(0,10).reshape(2,5)

In [27]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [29]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.random.rand(3,3)

array([[0.53453337, 0.86625338, 0.12620115, 0.9705605 , 0.88073983,
        0.2889608 , 0.64317741, 0.80582312, 0.56009098, 0.7964008 ]])

In [33]:
arr_ex=np.random.randn(3,3)

In [34]:
arr_ex

array([[ 0.53093577,  0.00504279,  0.15879356],
       [ 0.09804492, -2.08746659,  1.31529793],
       [ 0.44605728,  0.1950085 ,  0.15437588]])