In [2]:
import numpy as np

b=np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [17]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [18]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr.shape

(5,)

In [16]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [3]:
my_lst_1=[1,2,3,4,5]
my_lst_2=[6,7,8,9,10]
my_lst_3=[9,8,7,6,5]

arr=np.array([my_lst_1,my_lst_2,my_lst_3])

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [22]:
arr.shape

(3, 5)

In [23]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  9,  8],
       [ 7,  6,  5]])

After using reshape make sure that it will have the same numbers that in the list or else it gave error

Indexing

In [4]:
arr=np.array([1,2,3,4,5,6,7,8,9])


In [6]:
arr[-1]

np.int64(9)

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [20]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [24]:
arr[1:3,2:4]

array([[8, 9],
       [7, 6]])

In [27]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [12]:
arr=np.arange(0,10,2)

In [13]:
arr

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

Copy Function

In [17]:
arr[3:]=100

In [18]:
arr

array([  0,   2,   4, 100, 100])

In [9]:
arr1=arr

In [11]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [12]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [13]:
arr1=arr.copy()

In [14]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]
