In [1]:
import numpy as np

b=np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.shape

(5,)

In [5]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
my_lst_1=[1,2,3,4,5]
my_lst_2=[6,7,8,9,10]
my_lst_3=[9,8,7,6,5]

arr=np.array([my_lst_1,my_lst_2,my_lst_3])

In [7]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [8]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [9]:
arr.shape

(3, 5)

In [10]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  9,  8],
       [ 7,  6,  5]])

After using reshape make sure that it will have the same numbers that in the list or else it gave error

Indexing

In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9])


In [12]:
arr[-1]

np.int64(9)

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[1:3,2:4]

array([[8, 9],
       [7, 6]])

In [ ]:
arr[1:2,1:4]

In [ ]:
arr=np.arange(0,10,2)

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

Copy Function

In [17]:
arr[3:]=100

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [19]:
arr1=arr

In [20]:
arr1[3:]=500
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 9  8  7  6  5]]


In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [22]:
arr1=arr.copy()

In [23]:
print(arr)
arr1[3:]=1000
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 9  8  7  6  5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 9  8  7  6  5]]


In [24]:
val=2
arr[arr<300]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  9,  8,  7,  6,  5])

In [25]:
# Create arrays and reshape it

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
arr1=np.arange(0,10).reshape(2,5)

In [ ]:
arr2=np.arange(0,10).reshape(2,5)

In [27]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr1*arr2

In [29]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [30]:
np.random.rand(3,3)

array([[0.36761289, 0.9935499 , 0.08398164],
       [0.87394981, 0.25602223, 0.18304998],
       [0.57823681, 0.62390721, 0.24960223]])

In [31]:
arr_ex=np.random.randn(3,3)

In [32]:
arr_ex

array([[ 0.35939917,  0.63681537, -1.99337132],
       [ 1.24669999,  0.98108585,  0.2508522 ],
       [-2.35057819, -1.37964654, -0.05984551]])

In [33]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr3=np.zeros((2,3))


In [ ]:
arr3

In [35]:
arr4=np.ones((3,3))
arr4


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:

a=np.array([1,2])
b=np.array([1.])


In [38]:
a.dtype


dtype('int64')

In [39]:
b.dtype

dtype('float64')

In [ ]:
arr=np.array([1,2,3,4,5])
arr1=arr.astype(float)

In [ ]:
arr

In [ ]:
arr1

In [40]:
arr.itemsize

8

In [ ]:
arr1.itemsize


In [ ]:
arr1.dtype

In [ ]:
lista=range(100)
lista

In [41]:
arr=np.arange(25).reshape(5,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr[1:4,3:4]

array([[ 8],
       [13],
       [18]])

In [44]:
arr[2:3,2:3]

array([[12]])

In [ ]:
arr

In [ ]:
arr[1:3,:]

In [ ]:
arr[3:,3:]

Numpy Array Operation

In [15]:
import numpy as np

In [31]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([6,5,4,3,2,1])

In [32]:
arr1+arr2

array([7, 7, 7, 7, 7, 7])

In [33]:
arr1*arr2

array([ 6, 10, 12, 12, 10,  6])

In [26]:
arr2>3

array([ True,  True,  True, False, False, False])

In [35]:
#dot product

arr1.dot(arr2)

np.int64(56)

In [36]:
arr1.max()

np.int64(6)

In [37]:
arr1.min()

np.int64(1)

In [40]:
arr2.sum()

np.int64(21)

In [41]:
arr1.sum (axis=0)

np.int64(21)