In [1]:
import numpy as np

In [3]:

b=np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [37]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [38]:
arr

array([1, 2, 3, 4, 5])

In [39]:
arr.shape

(5,)

In [40]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [2]:
my_lst_1=[1,2,3,4,5]
my_lst_2=[6,7,8,9,10]
my_lst_3=[9,8,7,6,5]

arr=np.array([my_lst_1,my_lst_2,my_lst_3])

In [45]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [3]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [4]:
arr[1:2,2:3]

array([[8]])

In [27]:
arr.shape

(3, 5)

In [28]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  9,  8],
       [ 7,  6,  5]])

After using reshape make sure that it will have the same numbers that in the list or else it gave error

Indexing

In [42]:
arr=np.array([1,2,3,4,5,6,7,8,9])


In [30]:
arr[-1]

np.int64(9)

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[1:3,2:4]

array([[8, 9],
       [7, 6]])

In [ ]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [ ]:
arr=np.arange(0,10,2)

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

Copy Function

In [ ]:
arr[3:]=100

In [ ]:
arr

array([  0,   2,   4, 100, 100])

In [ ]:
arr1=arr

In [ ]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [ ]:
arr

array([  0,   2,   4, 500, 500])

In [ ]:
arr1=arr.copy()

In [ ]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [ ]:
val=2
arr[arr<300]

array([0, 2, 4])

In [ ]:
# Create arrays and reshape it

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr1=np.arange(0,10).reshape(2,5)

In [ ]:
arr2=np.arange(0,10).reshape(2,5)

In [ ]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [7]:
np.ones(4,dtype=complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [12]:
np.random.rand(3,3)

array([[0.75503467, 0.45246536, 0.98682416],
       [0.31109948, 0.89435649, 0.4201674 ],
       [0.82230448, 0.36439068, 0.6083383 ]])

In [ ]:
arr_ex=np.random.randn(3,3)

In [ ]:
arr_ex

array([[-0.6840202 ,  0.34089668, -0.34853709],
       [-2.1144717 , -0.91113669,  1.35394127],
       [-0.06950751, -2.05917028,  1.73980997]])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.zeros((2,3))


In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((3,3))
arr4


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:

a=np.array([1,2])
b=np.array([1.])


In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
arr=np.array([1,2,3,4,5])
arr1=arr.astype(float)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr1

array([1., 2., 3., 4., 5.])

In [ ]:
arr.itemsize

8

In [ ]:
arr1.itemsize


8

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
lista=range(100)
lista

range(0, 100)

In [13]:
arr=np.arange(25).reshape(5,5)

In [14]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:

arr[1:4,]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr[1:4,3:4]

array([[ 8],
       [13],
       [18]])

In [ ]:
arr[2:3,2:3]

array([[12]])

In [ ]:
arr

In [ ]:
arr[1:3,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr[3:,3:]

array([[18, 19],
       [23, 24]])

Numpy Array Operation

In [ ]:
import numpy as np

In [21]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([6,5,4,3,2,1])

In [22]:
arr1+arr2

array([7, 7, 7, 7, 7, 7])

In [23]:
arr1*arr2

array([ 6, 10, 12, 12, 10,  6])

In [26]:
arr2[arr2>3]

array([6, 5, 4])

In [27]:
arr2>4

array([ True,  True, False, False, False, False])

In [ ]:
#dot product

arr1.dot(arr2)

np.int64(56)

In [ ]:
arr1.max()

np.int64(6)

In [ ]:
arr1.min()

np.int64(1)

In [ ]:
arr2.sum()

np.int64(21)

In [ ]:
arr1.sum (axis=0)

np.int64(21)

In [ ]:
arr4=np.arange(0,9).reshape(3,3)

In [ ]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr4.min(axis=0)

array([0, 1, 2])

In [ ]:
arr4.max(axis=1)

array([2, 5, 8])

In [ ]:
arr4.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
arr4.sum(axis=1)

array([ 3, 12, 21])

In [ ]:
arr4.sum()

np.int64(36)

In [ ]:
arr4.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
arr4.sum(axis=1)

array([ 3, 12, 21])

In [ ]:
arr4.mean()

np.float64(4.0)

In [ ]:
np.median(arr4)

np.float64(4.0)

In [ ]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr4.ndim

2

**Reshaping Numpy Array**

In [ ]:
# Using ravel we get matrices 2,3,4,n dimensional in 1d
np.ravel(arr4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**transpose() is like Row becomes column and column become Row**

In [ ]:
arr4.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
arr5=np.arange(12,18).reshape(2,3)

In [ ]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

**Fancy Indexing**

In [ ]:
arr6=np.arange(24).reshape(6,4)

In [ ]:
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr6[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [ ]:
arr6[[2,3],[1,2]]

array([ 9, 14])

In [28]:
a = np.array([[1,2],[3,4]])


In [30]:
a

array([[1, 2],
       [3, 4]])

In [29]:
print(a[[0,1],[1,0]])

[2 3]


**Boolean Array**

In [ ]:
import numpy as np


In [31]:
arry=np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [32]:
arry

array([[40,  7, 99, 78, 68],
       [85, 29, 23, 17, 27],
       [89, 70, 49,  9, 27],
       [15, 46, 54, 96, 62]], dtype=int32)

In [ ]:
arry[0][2]

np.int32(13)

In [ ]:
arry>50

array([[False,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False,  True, False,  True,  True],
       [False, False,  True, False,  True]])

In [ ]:
# Indexing using Boolean array
arry[arry>50]

array([78, 95, 72, 98, 91, 51, 95, 65, 72], dtype=int32)

In [34]:
arry[(arry>50) & (arry%2==0)]

array([78, 68, 70, 54, 96, 62], dtype=int32)

In [ ]:
arry[(arry>50) & (arry%2==0)]=0

In [36]:
arry

array([[40,  7, 99,  0,  0],
       [85, 29, 23, 17, 27],
       [89,  0, 49,  9, 27],
       [15, 46,  0,  0,  0]], dtype=int32)

**Broadcasting**

In [ ]:
import numpy as np

In [3]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(10,20).reshape(2,5)

a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a1+a2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [7]:
a=np.array([[1],
            [2],
            [3]])
b=np.array([10,20])
print(a+b)

[[11 21]
 [12 22]
 [13 23]]


In [ ]:
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
arry=np.array([9,8,7],)

In [10]:
arr+arry

array([[10, 10, 10],
       [13, 13, 13],
       [16, 16, 16]])

**Some Important Functions in NumPy**
- `np.max(x)` - Returns the maximum value in an array.
- `np.min(x)` - Returns the minimum value in an array.
- `np.argmax(x)` - Returns the index of the maximum value in an array.
- `np.argmin(x)` - Returns the index of the minimum value in an array.

In [8]:
np.random.randint(1,20,4)

array([15, 19,  7, 17], dtype=int32)

In [14]:
np.random.random()

0.32998712508514305

In [17]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [28]:
x=np.random.randint(1,10,20).reshape(4,5)

In [ ]:
print(x)

[[9 3 4 2 3]
 [8 3 7 1 3]
 [7 7 3 8 8]
 [1 7 6 2 5]]


In [30]:
np.max(x)

np.int32(9)

In [31]:
np.min(x)

np.int32(1)

In [32]:
np.argmax(x)

np.int64(0)

In [33]:
np.argmin(x)

np.int64(8)

In [35]:
a=np.random.randint(1,30,5)

In [36]:
a

array([23, 17, 23,  6, 14], dtype=int32)

In [37]:
np.where(a%2==0, 'even', 'odd')

array(['odd', 'odd', 'odd', 'even', 'even'], dtype='<U4')

In [40]:
b=np.random.randint(1,100,10)

In [42]:
b

array([97, 84, 26, 15, 14, 85, 44,  7, 78, 57], dtype=int32)

In [43]:
np.sort(b)

array([ 7, 14, 15, 26, 44, 57, 78, 84, 85, 97], dtype=int32)

In [2]:
import numpy as np

In [3]:
a=np.arange(1,10)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
l=np.random.randint(0,100,16)
l.reshape(4,4)

array([[96, 58, 39, 70],
       [18, 85,  9, 20],
       [46, 31, 49, 48],
       [21, 92, 67, 66]], dtype=int32)

In [10]:
arr=np.random.rand(4,4)
print(arr)

[[0.52107119 0.91065338 0.31231235 0.73418773]
 [0.53570907 0.24141149 0.97190806 0.87244115]
 [0.9984752  0.52190749 0.04954306 0.3297786 ]
 [0.90338817 0.81094089 0.53159013 0.81601866]]


In [14]:
arr=np.array([10, 20, 30, 40, 50])
result=arr[arr>25]


In [15]:
print(result)


[30 40 50]
