In [1]:
import numpy as np

b=np.array([1,2,3,4])
print(b*2)

[2 4 6 8]


In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)
type(arr)

numpy.ndarray

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.shape

(5,)

In [5]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
my_lst_1=[1,2,3,4,5]
my_lst_2=[6,7,8,9,10]
my_lst_3=[9,8,7,6,5]

arr=np.array([my_lst_1,my_lst_2,my_lst_3])

In [17]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  9,  8],
       [ 7,  6,  5]])

After using reshape make sure that it will have the same numbers that in the list or else it gave error

Indexing

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9])


In [11]:
arr[-1]

np.int64(9)

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [ ]:
arr[1:3,2:4]

array([[8, 9],
       [7, 6]])

In [ ]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [ ]:
arr=np.arange(0,10,2)

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

Copy Function

In [ ]:
arr[3:]=100

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 9,  8,  7,  6,  5]])

In [ ]:
arr1=arr

In [ ]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [ ]:
arr

array([  0,   2,   4, 500, 500])

In [ ]:
arr1=arr.copy()

In [ ]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   2   4 500 500]
[   0    2    4 1000 1000]


In [ ]:
val=2
arr[arr<300]

array([0, 2, 4])

In [ ]:
# Create arrays and reshape it

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr1=np.arange(0,10).reshape(2,5)

In [ ]:
arr2=np.arange(0,10).reshape(2,5)

In [ ]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [ ]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [ ]:
np.random.rand(3,3)

array([[0.53453337, 0.86625338, 0.12620115, 0.9705605 , 0.88073983,
        0.2889608 , 0.64317741, 0.80582312, 0.56009098, 0.7964008 ]])

In [ ]:
arr_ex=np.random.randn(3,3)

In [ ]:
arr_ex

array([[ 0.53093577,  0.00504279,  0.15879356],
       [ 0.09804492, -2.08746659,  1.31529793],
       [ 0.44605728,  0.1950085 ,  0.15437588]])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.zeros((2,3))


In [ ]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((3,3))
arr4


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:

a=np.array([1,2])
b=np.array([1.])


In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
arr=np.array([1,2,3,4,5])
arr1=arr.astype(float)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr1

array([1., 2., 3., 4., 5.])

In [ ]:
arr.itemsize

8

In [ ]:
arr1.itemsize


8

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
lista=range(100)
lista

range(0, 100)

In [34]:
arr=np.arange(25).reshape(5,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr[1:4,3:4]

array([[ 8],
       [13],
       [18]])

In [40]:
arr[2:3,2:3]

array([[12]])

In [43]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr[1:3,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
arr[3:,3:]

array([[18, 19],
       [23, 24]])